apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-core.yaml
  - app-rollouts-controller.yaml
  - app-rollouts-governance.yaml
  - app-workflows-controller.yaml
  - app-workflow-definitions.yaml
