apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: estatewise-gitops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/hoangsonww/EstateWise-Chapel-Hill-Chatbot.git
